import termios
import tty
import sys
import select
"""Self-made console input library. Prolly shit"""

def isData():  #| Checks if there is any console input
	"""Checks if there is any console
	input. Might only work with Linux"""
	return select.select([sys.stdin], [], [], 0) == ([sys.stdin], [], [])

def passiveInput():  #| Only works for arrows
	"""Will return 'None' if no input
	is given, otherwise will retrieve
	ARROW input"""

	old_settings = termios.tcgetattr(sys.stdin)
	try:
		tty.setcbreak(sys.stdin.fileno())
		if isData(): return get_arrow()
		else: return None
	finally:
		termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)

def get_arrow():  #| Kinda janky. Think this would only work for bash
	"""Function that will handle arrow input.
	I'm not sure if it won't be janky sometimes;
	also might only work with bash! Also, due to
	some tinkering, might only work after setting
	up tty.setcbreak(sys.stdin.fileno()) and the
	other stuff"""

	while True:
		sys.stdin.read(1) #| Eat space generated by arrow keys
		direct = sys.stdin.read(2)
		if direct != '': break;
	if direct == "[A":  #| Up
		return 1
	elif direct == "[C":  #| Right
		return 2
	elif direct == "[B":  #| Down
		return 3
	elif direct == "[D":  #| Left
		return 4
	else: sys.exit("Arrow key input error")  #| If you have to handle a non-arrow key, don't

